# SonarScanner for MSBuild
# Build, QA

trigger:
- azure-pipelines

pool:
  vmImage: 'vs2017-win2016'

variables:
  group: sonarsource-build-variables
  solution: 'SonarScanner.MSBuild.sln'
  sonarCloudConnection: 'SonarCloud'
  sonarCloudOrganization: 'mickael-caro16778'
  sonarCloudMsBuildProjectKey: 'test-sonarscanner-msbuild'
  sonarCloudMsBuildProjectName: '[TEST]SonarScanner for MSBuild'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: Build solution
  jobs:
    - job: build
      displayName: 'Build and analyze on SonarCloud'
      steps:
      - checkout: self
        fetchDepth: 1
      - task: NuGetToolInstaller@1
        displayName: 'Use NuGet 4.9.3'
        inputs:
          versionSpec: '4.9.3'
      - task: NuGetCommand@2
        displayName: 'NuGet restore'
        inputs:
          command: 'restore'
          restoreSolution: '$(solution)'
          feedsToUse: 'select'
      - task: PowerShell@2
        displayName: 'Promote project version'
        inputs:
          targetType: 'inline'
          script: |
            # Calculate the file path
            $versionFilePath = "$env:BUILD_SOURCESDIRECTORY\scripts\version\Version.props"
            Write-Host "Reading the Sonar project version from '${versionFilePath}' ..."
            
            # Read the version from the file
            [xml]$versionProps = Get-Content "$versionFilePath"
            $sonarProjectVersion = $versionProps.Project.PropertyGroup.MainVersion
            Write-Host "Sonar project version is '${sonarProjectVersion}'"
            
            # Set the variable to it can be used by other tasks
            Write-Host "##vso[task.setvariable variable=SONAR_PROJECT_VERSION;]$sonarProjectVersion"

      - task: PowerShell@2
        displayName: 'Execute CI build script'
        inputs:
          filePath: 'scripts\\build\\ci-build.ps1'
      - task: SonarCloudPrepare@1
        condition: and(succeeded(), or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranchName'], 'master')))
        inputs: 
          SonarCloud: '$(sonarCloudConnection)'
          organization: '$(sonarCloudOrganization)'
          projectKey: '$(sonarCloudMsBuildProjectKey)'
          projectName: '$(sonarCloudMsBuildProjectName)'
          projectVersion: '$(SONAR_PROJECT_VERSION)'
          scannerMode: MSBuild
      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          vsVersion: '15.0'
          platform: '$(BuildPlatform)'
          configuration: '$(BuildConfiguration)'
          maximumCpuCount: true
          #msbuildArgs: '/p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /p:defineConstants="SignAssembly" /p:SignAssembly=true /p:AssemblyOriginatorKeyFile="$(snk.secureFilePath)"'
      - task: VSTest@2
        inputs:
          testSelector: 'testAssemblies'
          testAssemblyVer2: |
            **\$(BuildConfiguration)\*test*.dll
            !**\obj\**
          searchFolder: '$(System.DefaultWorkingDirectory)'
          vsTestVersion: '15.0'
          codeCoverageEnabled: true
      - task: PowerShell@2
        displayName: 'Delete files created by unit tests'
        inputs:
          targetType: 'inline'
          script: |
            Write-Host "Delete files created by unit tests, so that they will not be taken by the SonarCloud analysis."

            $files = Get-ChildItem env:TEST_FILE_TO_DELETE
            $listOfFiles = $files.Split(";;")
            foreach ($file in $listOfFiles) {
              if([System.IO.File]::Exists($file))
              {
                Remove-Item -Path $file
              }
            }
      - task: SonarCloudAnalyze@1
        condition: and(succeeded(), or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranchName'], 'master')))
      - task: SonarCloudPublish@1
        condition: and(succeeded(), or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranchName'], 'master')))
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'DeploymentArtifacts/BuildAgentPayload/$(BuildConfiguration)'
          artifact: 'scanner-zips'

- stage: QA
  displayName: Run Integration tests
  dependsOn: Build
  jobs:
  - job: its
    displayName: 'Run its'
    strategy: 
      matrix: 
        vs2015_dev: 
          imageName: "vs2015-win2012r2"
          SQ_VERSION: "DEV"
          MSBUILD_PATH: "C:\\Program Files (x86)\\MSBuild\\14.0\\Bin\\msbuild.exe"
        vs2015_latest67: 
          imageName: "vs2015-win2012r2"
          SQ_VERSION: "LATEST_RELEASE[6.7]"
          MSBUILD_PATH: "C:\\Program Files (x86)\\MSBuild\\14.0\\Bin\\msbuild.exe"
        vs2015_latest79: 
          imageName: "vs2015-win2012r2"
          SQ_VERSION: "LATEST_RELEASE[7.9]"
          MSBUILD_PATH: "C:\\Program Files (x86)\\MSBuild\\14.0\\Bin\\msbuild.exe"
        vs2017_dev: 
          imageName: "vs2017-win2016"
          SQ_VERSION: "DEV"
          MSBUILD_PATH: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\15.0\\Bin\\msbuild.exe"
        vs2017_latest67: 
          imageName: "vs2017-win2016"
          SQ_VERSION: "LATEST_RELEASE[6.7]"
          MSBUILD_PATH: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\15.0\\Bin\\msbuild.exe"
        vs2017_latest79: 
          imageName: "vs2017-win2016"
          SQ_VERSION: "LATEST_RELEASE[7.9]"
          MSBUILD_PATH: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\15.0\\Bin\\msbuild.exe"
      maxParallel: 2
    steps:
      - checkout: self
        fetchDepth: 1
      - task: DownloadSecureFile@1
        displayName: 'Download Maven private settings'
        name: mavenSettings
        inputs:
          secureFile: 'maven-settings-private-with-p2-mirrors.xml'
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          itemPattern: '*.zip'
          targetPath: '$(Pipeline.Workspace)'
          artifactName: scanner-zips
      - task: Maven@3
        displayName: 'Run Maven verify'
        inputs:
          goals: 'verify'
          options: '--settings $(mavenSettings.secureFilePath) -B -e -Dsonar.runtimeVersion=$SQ_VERSION -DscannerForMSBuild.version=$SCANNER_VERSION.$(Build.BuildId) -Dmsbuild.path=$MSBUILD_PATH'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          mavenOptions: '-Xmx3072m'

- stage: DeployToTest
  displayName: Deploy to test environment
  dependsOn: 
  - Build
  - QA
  jobs:
  - deployment: deploy_chocolatey_test
    displayName: Deploy to Chocolatey (Test)
    variables:
     pipelineArtifactOutputPath: $(Pipeline.Workspace)/scanner-zips
    pool:
      vmImage: 'windows-latest'
    # creates an environment if it doesn't exist
    environment: 'ScannerForMsBuild-Test'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            enabled: false
            inputs:
              buildType: 'current'
              itemPattern: '*.nupkg'
              targetPath: '$(Pipeline.Workspace)'
              artifactName: 'scanner-zips'
          - task: PowerShell@2
            displayName: "Install chocolatey"
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "Installing chocolatey...."
                Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
                Write-Host "Choco is ready to use !"
          - task: PowerShell@2
            enabled: false
            displayName: "Push .Net Fwk 46 package to chocolatey"
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "Publishing .net 46 package...."
                choco push $(pipelineArtifactOutputPath)/sonarscanner-msbuild-net46.$(build.SONAR_PROJECT_VERSION).$(Build.BuildId).nupkg -k $CHOCO_TEST_API_KEY -source "https://chocolatey.org/" --yes --whatif
          - task: PowerShell@2
            enabled: false
            displayName: "Push .Net Core 2 package to chocolatey"
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "Installing chocolatey...."
                choco push $(pipelineArtifactOutputPath)/sonarscanner-msbuild-netcoreapp2.0.$(build.SONAR_PROJECT_VERSION).$(Build.BuildId).nupkg -k $CHOCO_TEST_API_KEY -source "https://chocolatey.org/" --yes --whatif
  - deployment: deploy_github_test
    displayName: Deploy to GitHub (Test)
    variables:
     pipelineArtifactOutputPath: $(Pipeline.Workspace)/scanner-zips
    pool:
      vmImage: 'windows-latest'
    # creates an environment if it doesn't exist
    environment: 'ScannerForMsBuild-Test'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              itemPattern: 
              targetPath: '$(Pipeline.Workspace)'
              artifactName: 'scanner-zips'
          - task: GitHubRelease@1
            enabled: false
            inputs:
              gitHubConnection: 'Github'
              repositoryName: '$(Build.Repository.Name)'
              action: 'create'
              target: '$(Build.SourceVersion)'
              tagSource: 'userSpecifiedTag'
              title: '$(SONAR_PROJECT_VERSION)'
              releaseNotesSource: 'inline'
              addChangeLog: false